#!/bin/csh -f

# Remove existing library if present
if ( -f libswift.a ) then
  rm libswift.a
endif

echo
echo DIRECTORY: anal
cd anal
csh -f ../@make_libswift

echo DIRECTORY: bs
cd ../bs
csh -f ../@make_libswift

echo DIRECTORY: coord
cd ../coord
csh -f ../@make_libswift

echo DIRECTORY: discard
cd ../discard
csh -f ../@make_libswift

echo DIRECTORY: io
cd ../io
csh -f ../@make_libswift

echo DIRECTORY: lyap
cd ../lyap
csh -f ../@make_libswift

echo DIRECTORY: lyap2
cd ../lyap2
csh -f ../@make_libswift

echo DIRECTORY: mvs/drift
cd ../mvs
cd drift
csh -f ../../@make_libswift

echo DIRECTORY: mvs/getacch
cd ../getacch
csh -f ../../@make_libswift

echo DIRECTORY: mvs/kickvh
cd ../kickvh
csh -f ../../@make_libswift

echo DIRECTORY: mvs/step
cd ../step
csh -f ../../@make_libswift
cd ..

echo DIRECTORY: orbel
cd ../orbel
csh -f ../@make_libswift

echo DIRECTORY: rmvs
cd ../rmvs
csh -f ../@make_libswift

echo DIRECTORY: rmvs2
cd ../rmvs2
csh -f ../@make_libswift

echo DIRECTORY: rmvs3
cd ../rmvs3
csh -f ../@make_libswift

echo DIRECTORY: rmvs4
cd ../rmvs4
csh -f ../@make_libswift

echo DIRECTORY: tu4
cd ../tu4
csh -f ../@make_libswift

echo DIRECTORY: obl
cd ../obl
csh -f ../@make_libswift

echo DIRECTORY: util
cd ../util
csh -f ../@make_libswift

echo DIRECTORY: helio
cd ../helio
csh -f ../@make_libswift

echo DIRECTORY: symba5
cd ../symba5
csh -f ../@make_libswift

echo DIRECTORY: skeel
cd ../skeel
csh -f ../@make_libswift

# Build and index the static library
cd ..
ar ts libswift.a
ranlib libswift.a

echo DONE
echo
