#!/bin/sh

# @makeall_libswift — Master build script for the Swift N-body integrator
# library. Compiles all Fortran source files across subdirectories and archives
# them into libswift.a.
#
# This script is called by setup.sh or can be run directly:
#   sh @makeall_libswift
#
# Each subdirectory is compiled using the @make_libswift script located
# in the swift root directory. This @make_libswift is created by setup.sh.

# Remove existing library if present
if [ -f libswift.a ]; then
  rm libswift.a
fi

echo
echo DIRECTORY: anal
cd anal
sh ../@make_libswift

echo DIRECTORY: bs
cd ../bs
sh ../@make_libswift

echo DIRECTORY: coord
cd ../coord
sh ../@make_libswift

echo DIRECTORY: discard
cd ../discard
sh ../@make_libswift

echo DIRECTORY: io
cd ../io
sh ../@make_libswift

echo DIRECTORY: lyap
cd ../lyap
sh ../@make_libswift

echo DIRECTORY: lyap2
cd ../lyap2
sh ../@make_libswift

echo DIRECTORY: mvs/drift
cd ../mvs
cd drift
sh ../../@make_libswift

echo DIRECTORY: mvs/getacch
cd ../getacch
sh ../../@make_libswift

echo DIRECTORY: mvs/kickvh
cd ../kickvh
sh ../../@make_libswift

echo DIRECTORY: mvs/step
cd ../step
sh ../../@make_libswift
cd ..

echo DIRECTORY: orbel
cd ../orbel
sh ../@make_libswift

echo DIRECTORY: rmvs
cd ../rmvs
sh ../@make_libswift

echo DIRECTORY: rmvs2
cd ../rmvs2
sh ../@make_libswift

echo DIRECTORY: rmvs3
cd ../rmvs3
sh ../@make_libswift

echo DIRECTORY: rmvs4
cd ../rmvs4
sh ../@make_libswift

echo DIRECTORY: tu4
cd ../tu4
sh ../@make_libswift

echo DIRECTORY: obl
cd ../obl
sh ../@make_libswift

echo DIRECTORY: util
cd ../util
sh ../@make_libswift

echo DIRECTORY: helio
cd ../helio
sh ../@make_libswift

echo DIRECTORY: symba5
cd ../symba5
sh ../@make_libswift

echo DIRECTORY: skeel
cd ../skeel
sh ../@make_libswift

# Build and index the static library
cd ..
ar ts libswift.a
ranlib libswift.a

echo DONE
echo
